/*
Group_Name: Final Project 96
Names: Snehitha Sai Sappa, Hitesh Koneru
Class: IFT 530
Date :04/24/2024
Assignment: Final Project
*/

DROP SCHEMA IF EXISTS Tourism_Management_System;
CREATE SCHEMA Tourism_Management_System;

CREATE TABLE Tourist (
    TouristID INT AUTO_INCREMENT PRIMARY KEY,
    Fname VARCHAR(10) NOT NULL,
    Lname VARCHAR(10) NOT NULL,
    Email VARCHAR(20) NOT NULL,
    Phone NUMERIC(10) NOT NULL,
    IsActive BOOLEAN DEFAULT TRUE,
    Gender CHAR(1) CHECK (Gender IN ('M', 'F', 'O')),
    Age INT
);

CREATE TABLE BOOKING (
    BID INT PRIMARY KEY AUTO_INCREMENT,
    TouristID INT NOT NULL,
    Booking_Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TripStart_Date DATE NOT NULL,
    TripEnd_Date DATE NOT NULL,
    Amount FLOAT,
    FOREIGN KEY (TouristID) REFERENCES Tourist(TouristID) ON DELETE CASCADE
);

CREATE TABLE PACKAGE (
    PACKAGEID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(15) NOT NULL,
    DURATION INT,
    NO_OF_PEOPLE INT,
    IsActive BOOLEAN DEFAULT TRUE,
    AMOUNT FLOAT
);

CREATE TABLE TOURIST_SPOTS (
    SPOTID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(20) NOT NULL,
    SEASON VARCHAR(10),
    RATINGS FLOAT CHECK (RATINGS >= 0 AND RATINGS <= 5),
    ADDRESS VARCHAR(100),
    PINCODE NUMERIC(6)
);

CREATE TABLE GUIDE (
    GUIDEID INT PRIMARY KEY AUTO_INCREMENT,
    Fname VARCHAR(10) NOT NULL,
    Lname VARCHAR(10) NOT NULL,
    Email VARCHAR(20),
    Phone NUMERIC(10) NOT NULL,
    Gender CHAR(1) CHECK (Gender IN ('M', 'F', 'O')),
    Age INT,
    ADDRESS VARCHAR(100),
    PINCODE NUMERIC(6)
);

CREATE TABLE RESTAURANT (
    RID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(50) NOT NULL,
    Phone NUMERIC(10),
    FoodType VARCHAR(20) CHECK (FoodType IN ('VEG', 'NON-VEG', 'BOTH')),
    Ratings FLOAT CHECK (Ratings >= 0 AND Ratings <= 5),
    Address VARCHAR(100),
    Pincode NUMERIC(6)
);

CREATE TABLE HOTEL (
    HOTELID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(50) NOT NULL,
    City VARCHAR(50) NOT NULL,
    PHONE NUMERIC(10),
    FOODTYPE VARCHAR(20) CHECK (FOODTYPE IN ('VEG', 'NON-VEG', 'BOTH')),
    RATINGS FLOAT CHECK (RATINGS >= 0 AND RATINGS <= 5),
    ADDRESS VARCHAR(100),
    IsActive BOOLEAN DEFAULT TRUE,
    PINCODE NUMERIC(6)
);

CREATE TABLE ROOM (
    HOTELID INT NOT NULL,
    ROOM_NO DECIMAL(3, 0) NOT NULL,
    Type VARCHAR(6) CHECK (Type IN ('AC', 'NON-AC', 'HEATER')),
    BEDS INT CHECK (BEDS > 0),
    CAPACITY INT CHECK (CAPACITY > 0),
    RATE FLOAT,
    STATUS VARCHAR(15) CHECK (STATUS IN ('AVAILABLE', 'NOT-AVAILABLE', 'BOOKED')),
    PRIMARY KEY (HOTELID, ROOM_NO),
    FOREIGN KEY (HOTELID) REFERENCES HOTEL(HOTELID)
);

CREATE TABLE PACKAGE_INCLUDES_SPOTS (
    PACKAGEID INT,
    SPOTID INT,
    PRIMARY KEY (PACKAGEID, SPOTID),
    FOREIGN KEY (PACKAGEID) REFERENCES PACKAGE(PACKAGEID) ON DELETE CASCADE,
    FOREIGN KEY (SPOTID) REFERENCES TOURIST_SPOTS(SPOTID) ON DELETE CASCADE
);

CREATE TABLE PACKAGE_INCLUDES_GUIDES (
    PACKAGEID INT,
    GUIDEID INT,
    PRIMARY KEY (PACKAGEID, GUIDEID),
    FOREIGN KEY (PACKAGEID) REFERENCES PACKAGE(PACKAGEID) ON DELETE CASCADE,
    FOREIGN KEY (GUIDEID) REFERENCES GUIDE(GUIDEID) ON DELETE CASCADE
);
