/*
Group_Name: Final Project 96
Names: Snehitha Sai Sappa, Hitesh Koneru
Class: IFT 530
Date :04/24/2024
Assignment: Final Project
*/

DELIMITER $$

CREATE TRIGGER tourist_spots_insert_trigger
AFTER INSERT ON TOURIST_SPOTS
FOR EACH ROW
BEGIN
    INSERT INTO TOURIST_SPOTS_AUDIT (SPOTID, Name, SEASON, RATINGS, ADDRESS, PINCODE, ACTION)
    VALUES (NEW.SPOTID, NEW.Name, NEW.SEASON, NEW.RATINGS, NEW.ADDRESS, NEW.PINCODE, 'Insert');
END$$

CREATE TRIGGER tourist_spots_update_trigger
AFTER UPDATE ON TOURIST_SPOTS
FOR EACH ROW
BEGIN
    INSERT INTO TOURIST_SPOTS_AUDIT (SPOTID, Name, SEASON, RATINGS, ADDRESS, PINCODE, ACTION)
    VALUES (NEW.SPOTID, NEW.Name, NEW.SEASON, NEW.RATINGS, NEW.ADDRESS, NEW.PINCODE, 'Update');
END$$

CREATE TRIGGER tourist_spots_delete_trigger
AFTER DELETE ON TOURIST_SPOTS
FOR EACH ROW
BEGIN
    INSERT INTO TOURIST_SPOTS_AUDIT (SPOTID, Name, SEASON, RATINGS, ADDRESS, PINCODE, ACTION)
    VALUES (OLD.SPOTID, OLD.Name, OLD.SEASON, OLD.RATINGS, OLD.ADDRESS, OLD.PINCODE, 'Delete');
END$$

DELIMITER ;
